fix cve Security issues
streamnative/pulsar-flink pull request #306
Opened 2021-04-27 16:01 UTC by jianyun8023

fixed #305

2021-04-30 06:32 UTC, jianyun8023 commented on pulsar-flink-connector/src/test/java/org/apache/flink/streaming/connectors/pulsar/testutils/PulsarContainer.java
> +public class PulsarContainer extends GenericContainer<PulsarContainer> {
The reason for adding it is that the PulsarContainer provided by testcontainers can only use the `apachepulsar/pulsar` docker image.

2021-04-30 07:22 UTC, syhily requested changes
I don't like maintaining a pulsar container here.
The issue could be worked around by defining `DockerImageName`

2021-05-03 10:16 UTC, codelipenghui approved these changes

2021-05-03 10:37 UTC, syhily approved these changes
LGTM

2021-05-03 10:38 UTC, merged