fix cursor not available when restore state
streamnative/pulsar-flink pull request #308
Opened 2021-04-29 01:11 UTC by jianyun8023

fixed #300

2021-05-03 10:56 UTC, syhily requested changes

2021-05-03 10:56 UTC, syhily commented on pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarSource.java
> +    private MessageId checkAndLoadAvailableCursorState(String topic, MessageId messageId) {
This logic is under discussion, we don't check the cursor status. Instead, we give user option to set their own cursor.

2021-05-03 10:56 UTC, syhily commented on pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarSource.java
> +                    .forEach(e -> ownedTopicStarts.put(e.f0, e.f1));
Use `toMap` instead?

2021-05-03 10:56 UTC, syhily commented on pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarOptions.java
> +    public static final String RECOVERY_CURSOR_WHEN_CURSOR_LOST = "recovery-cursor-when-cursor-lost";
This naming is not a good choice.

2021-05-03 10:56 UTC, syhily commented on pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/SourceSinkUtils.java
> +        final String[] split = value.split(":");
Use splitter and add an extra trim?

2021-05-06 19:19 UTC, jianyun8023 commented
Inappropriate solution, the new solution has #319 fixes.

2021-05-06 19:19 UTC, closed without merging