Support cdc delete message.
streamnative/pulsar-flink pull request #316
Opened 2021-05-04 10:00 UTC by MINCWANG

Support cdc delete message.

The previous code cannot read the delete message, because the length of the delete message is 0

2021-05-04 12:08 UTC, syhily requested changes
The logic should be improved.

2021-05-04 12:08 UTC, syhily commented on pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/table/DynamicPulsarDeserializationSchema.java
> +        if (message.getData() == null || data.length == 0 && upsertMode) {
`if ((message.getData() == null || data.length == 0) && upsertMode) {`

2021-05-10 07:38 UTC, wolfstudy commented
@syhily Hello, PTAL again thanks.

2021-05-10 07:39 UTC, wolfstudy commented
@MINCWANG Can you help to check the action CI?

2021-05-10 13:18 UTC, MINCWANG commented
@wolfstudy @syhily  Hi, How do i restart CI? thks

2021-05-11 01:44 UTC, syhily commented
> @wolfstudy @syhily Hi, How do i restart CI? thks.. CI have a error for UT

The UT has been restarted. You can restart the UT in `Checks` tab.

2021-05-11 02:43 UTC, jianyun8023 commented
> > @wolfstudy @syhily Hi, How do i restart CI? thks.. CI have a error for UT
> 
> The UT has been restarted. You can restart the UT in `Checks` tab.

@syhily I'll fix this error. I guess it is caused by the change of MessageId sequence in pulsar 2.7.1.

2021-05-13 02:56 UTC, MINCWANG commented
> > > @wolfstudy @syhily Hi, How do i restart CI? thks.. CI have a error for UT
> > 
> > 
> > The UT has been restarted. You can restart the UT in `Checks` tab.
> 
> @syhily I'll fix this error. I guess it is caused by the change of MessageId sequence in pulsar 2.7.1.

@jianyun8023 Thanks, please help me restart CI when you fix this error

2021-05-13 19:32 UTC, jianyun8023 approved these changes

2021-05-20 04:06 UTC, syhily approved these changes

2021-05-20 04:06 UTC, merged